# Generated by Django 4.2.11 on 2024-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
