# Generated by Django 4.2.11 on 2024-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0002_aboutme_description_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
