# Generated by Django 4.2.11 on 2024-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0003_alter_aboutme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='', upload_to='images/mathatx'),
        ),
    ]
