# Generated by Django 4.2.11 on 2024-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0004_banner_alter_aboutme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', upload_to='images/mathatx/banners'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default='', upload_to='images/mathatx/aboutme'),
        ),
    ]
