# Generated by Django 4.2.11 on 2024-07-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0005_banner_image_alter_aboutme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=2000)),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=1000)),
                ('stars', models.PositiveSmallIntegerField()),
                ('source', models.URLField(default='https://maps.app.goo.gl/Xr7ZFPE7oEd7eE2PA')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='images/mathatx/services')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
