# Generated by Django 5.0.6 on 2024-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0006_faq_review_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', null='', upload_to='images/mathatx/services'),
        ),
    ]
