# Generated by Django 5.0.6 on 2024-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathatx', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='info_multiple_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_sliding_scale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='info_virtual_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
